# Generated by Django 5.2.17 on 2026-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='member_name_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='member_active_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['payment_due_date'], name='member_due_idx'),
        ),
    ]
